set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "" FORCE)
set(CMAKE_CACHEFILE_DIR "c:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/build-Fusion for STM32 @ 168 MHz" CACHE STRING "" FORCE)
set(CMAKE_CACHE_MAJOR_VERSION "3" CACHE STRING "" FORCE)
set(CMAKE_CACHE_MINOR_VERSION "21" CACHE STRING "" FORCE)
set(CMAKE_CACHE_PATCH_VERSION "3" CACHE STRING "" FORCE)
set(CMAKE_COMMAND "C:/NECTOStudio/NECTOStudio/CMake/bin/cmake.exe" CACHE STRING "" FORCE)
set(CMAKE_CPACK_COMMAND "C:/NECTOStudio/NECTOStudio/CMake/bin/cpack.exe" CACHE STRING "" FORCE)
set(CMAKE_CTEST_COMMAND "C:/NECTOStudio/NECTOStudio/CMake/bin/ctest.exe" CACHE STRING "" FORCE)
set(CMAKE_EXPORT_COMPILE_COMMANDS "1" CACHE STRING "" FORCE)
set(CMAKE_EXTRA_GENERATOR "" CACHE STRING "" FORCE)
set(CMAKE_GENERATOR "Ninja" CACHE STRING "" FORCE)
set(CMAKE_GENERATOR_INSTANCE "" CACHE STRING "" FORCE)
set(CMAKE_GENERATOR_PLATFORM "" CACHE STRING "" FORCE)
set(CMAKE_GENERATOR_TOOLSET "" CACHE STRING "" FORCE)
set(CMAKE_HOME_DIRECTORY "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/LCD_example" CACHE STRING "" FORCE)
set(CMAKE_MAKE_PROGRAM "C:/NECTOStudio/NECTOStudio/ninja.exe" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER "C:/NECTOStudio/NECTOStudio/compilers/ARM/mikroC/mikroCARM.exe" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_FORCED "TRUE" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_ID "mikroC" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_ID_RUN "TRUE" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_WORKS "TRUE" CACHE STRING "" FORCE)
set(CMAKE_NUMBER_OF_MAKEFILES "1" CACHE STRING "" FORCE)
set(CMAKE_PLATFORM_INFO_INITIALIZED "1" CACHE STRING "" FORCE)
set(CMAKE_PROJECT_DESCRIPTION "" CACHE STRING "" FORCE)
set(CMAKE_PROJECT_HOMEPAGE_URL "" CACHE STRING "" FORCE)
set(CMAKE_PROJECT_NAME "LCD_example" CACHE STRING "" FORCE)
set(CMAKE_ROOT "C:/NECTOStudio/NECTOStudio/CMake/share/cmake-3.21" CACHE STRING "" FORCE)
set(CMAKE_SKIP_INSTALL_RPATH "NO" CACHE STRING "" FORCE)
set(CMAKE_SKIP_RPATH "NO" CACHE STRING "" FORCE)
set(CMAKE_TOOLCHAIN_FILE "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/build-Fusion for STM32 @ 168 MHz/toolchain.cmake" CACHE STRING "" FORCE)
set(CMAKE_VERBOSE_MAKEFILE "FALSE" CACHE STRING "" FORCE)
set(CMAKE_mikroC_COMPILER_WORKS "1" CACHE STRING "" FORCE)
set(CORE_LIB "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/.meproject/setup/Debug/lib/lib_core.a" CACHE STRING "" FORCE)
set(CORE_NAME "M4EF" CACHE STRING "" FORCE)
set(FIND_PACKAGE_MESSAGE_DETAILS_MikroC.System "["C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/.meproject/setup/Debug/cmake/../bin/STM/ST M4/__Lib_System_011/MikroC.System.a"][v()]" CACHE STRING "" FORCE)
set(JCFG_FILE "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/.meproject/setup/Debug/STM32F407ZG.jcfg" CACHE STRING "" FORCE)
set(LCD_example_BINARY_DIR "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/build-Fusion for STM32 @ 168 MHz" CACHE STRING "" FORCE)
set(LCD_example_IS_TOP_LEVEL "ON" CACHE STRING "" FORCE)
set(LCD_example_SOURCE_DIR "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example" CACHE STRING "" FORCE)
set(LEGACY_LIBRARIES ""C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/.meproject/setup/Debug/cmake/../bin/STM/ST M4/__Lib_System_011/MikroC.System.a"" CACHE STRING "" FORCE)
set(MCU_NAME "STM32F407ZG" CACHE STRING "" FORCE)
set(MIKROSDK_TYPE "legacy" CACHE STRING "" FORCE)
set(MSDK_BUILD_TFT_MODULES "FALSE" CACHE STRING "" FORCE)
set(NECTO_DESIGNER_GENERATOR_PATH "C:/NECTOStudio/NECTOStudio/vtft_generator.exe" CACHE STRING "" FORCE)
set(OSC "168" CACHE STRING "" FORCE)
set(PROJECT_TYPE "legacy" CACHE STRING "" FORCE)
set(SEARCH_PATHS "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/build-Fusion for STM32 @ 168 MHz;C:/NECTOStudio/NECTOStudio/compilers/ARM/mikroC/core/def;C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example" CACHE STRING "" FORCE)
set(TOOLCHAIN_ID "mikrocarm" CACHE STRING "" FORCE)
set(TOOLCHAIN_LANGUAGE "MikroC" CACHE STRING "" FORCE)
set(_MSDK_BOARD_NAME_ "BOARD_FUSION_FOR_STM32_V8" CACHE STRING "" FORCE)
set(_MSDK_DIP_SOCKET_TYPE_ "" CACHE STRING "" FORCE)
set(_MSDK_HAL_LOW_LEVEL_TARGET_ "mikroe" CACHE STRING "" FORCE)
set(_MSDK_MCU_CARD_NAME_ "MCU_CARD_FOR_STM32" CACHE STRING "" FORCE)
set(_MSDK_PACKAGE_NAME_ "Tx" CACHE STRING "" FORCE)
set(TOOLCHAIN_ID "mikrocarm" CACHE STRING "" FORCE)
set(OSC "168" CACHE STRING "" FORCE)


set(COMPILER_FLAGS -C -SSA -MF -O11111114   "-DBG")
set(LINKER_FLAGS -C -SSA -MF -O11111114   "-DBG")

string(TOLOWER ${CMAKE_BUILD_TYPE} build_type)
if (build_type STREQUAL debug)
    list(APPEND COMPILER_FLAGS "-UICD")
    list(APPEND LINKER_FLAGS "-UICD")
endif()

file(TO_CMAKE_PATH "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/.meproject/setup/Debug/STM32F407ZG.jcfg" JCFG_FILE_VAL)
set(JCFG_FILE  ${JCFG_FILE_VAL} CACHE STRING "" FORCE)

file(TO_CMAKE_PATH "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/.meproject/setup/Debug/lib/lib_core.a" CORE_LIB_VAL)
set(CORE_LIB ${CORE_LIB_VAL} CACHE STRING "" FORCE)

set(SEARCH_PATHS "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/build-Fusion for STM32 @ 168 MHz;C:/NECTOStudio/NECTOStudio/compilers/ARM/mikroC/core/def;C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example" CACHE STRING "" FORCE)

set(CMAKE_MikroC_COMPILER "C:/NECTOStudio/NECTOStudio/compilers/ARM/mikroC/mikroCARM.exe" CACHE INTERNAL "")
set(CMAKE_MikroC_COMPILER_ID "mikroC" CACHE INTERNAL "")

set(CMAKE_MikroC_OUTPUT_EXTENSION_REPLACE 1)
set(CMAKE_MikroC_OUTPUT_EXTENSION ".emcl")

# set CMAKE_SYSTEM_NAME to define build as CMAKE_CROSSCOMPILING
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_MikroC_COMPILER_WORKS TRUE CACHE INTERNAL "")
SET(CMAKE_MikroC_COMPILER_FORCED TRUE CACHE INTERNAL "")
SET(CMAKE_MikroC_COMPILER_ID_RUN TRUE CACHE INTERNAL "")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# add compiler option flags
add_compile_options(${COMPILER_FLAGS})
# add link option flags
add_link_options(${LINKER_FLAGS})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

file(TO_CMAKE_PATH "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/.meproject/setup/Debug/lib/cmake" MIKROSDK_PATH)
file(TO_CMAKE_PATH "C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/.meproject/setup/Debug/lib/cmake" MIKROC_CORE_PATH)


set(MIKROSDK_ROOT_PATH ${MIKROSDK_PATH})
set(MIKROC_CORE_ROOT_PATH ${MIKROC_CORE_PATH})
#append to cmake_prefix_path
list(APPEND CMAKE_PREFIX_PATH ${MIKROSDK_ROOT_PATH})
list(APPEND CMAKE_PREFIX_PATH ${MIKROC_CORE_ROOT_PATH})

list(APPEND CMAKE_MODULE_PATH "C:/Users/footb/AppData/Local/MIKROE/NECTOStudio2/cmake;C:/Users/footb/Documents/MIKROE/Week_1/Lecture_1/LCD_example/.meproject/setup/Debug/cmake;")